### PR TITLE
M6 friendships v2

### PR DESCRIPTION
**Pull request by redacuve**
This is the pull request from the 6th milestone of the final project of RoR

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work team! @redacuve annd @aecordova 
This is awesome work from you two :handshake: Please include a link to the deployed project on heroku as this milestone is centered around that. I wish you the very best and see you at the top! :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by aecordova** [comment]
Hi @Oluwadamilareolusakin, We thought that was part of the next milestone, but here is the link anyway.... [Deployed App](https://mighty-basin-95377.herokuapp.com/users/sign_in)

**Comment by nikasulo** [comment]
@aecordova You are correct! I made a mistake, I am sorry for the time and confusion that caused you and thank you for bringing this to my notice!

**Comment by aecordova** [comment]
@Oluwadamilareolusakin no problem at all, should we re-submit the review?

**Review by nikasulo — APPROVED** [review]
# Great job! @redacuve and @aecordova :rocket: 
You have done beautiful work! Please merge and keep moving forward :handshake: I wish you the very best and see you at the top!

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
